In [8]:
import torch

x = torch.zeros(2, 2, 2)
y = torch.empty(2, 2, 2)
x, y

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 tensor([[[0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],
 
         [[2.3640e+14, 1.4013e-45],
          [0.0000e+00, 0.0000e+00]]]))

In [11]:
print(x.size())
x.shape

torch.Size([2, 2, 2])


torch.Size([2, 2, 2])

In [13]:
x = torch.tensor([1,3,5,7], dtype= torch.float64)
x

tensor([1., 3., 5., 7.], dtype=torch.float64)

In [18]:
x = torch.ones(2,2)
y = torch.ones(2,2)
print(x+y)
print(y)
y.add_(x)
print(y)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [27]:
print(y.size())
print(y.view(4, -1).size())

torch.Size([2, 2])
torch.Size([4, 1])


In [34]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
x = torch.rand(2,2,2,2,)
x = x.to(device)
print(device)
print(x, x.device)

mps
tensor([[[[0.8533, 0.8358],
          [0.3470, 0.7557]],

         [[0.4772, 0.3056],
          [0.2351, 0.2489]]],


        [[[0.6525, 0.4228],
          [0.4391, 0.7473]],

         [[0.4700, 0.2101],
          [0.3870, 0.0651]]]], device='mps:0') mps:0


In [54]:
x = torch.ones(3, requires_grad=True)
y = x + 0
print(x)
print(y)
print(y.grad_fn)

tensor([1., 1., 1.], requires_grad=True)
tensor([1., 1., 1.], grad_fn=<AddBackward0>)


In [55]:
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)
tensor(3., grad_fn=<MeanBackward0>)


In [56]:
print(x.grad)
z.backward()
print(x.grad)

None
tensor([2., 2., 2.])
