In [8]:
import torch

x = torch.zeros(2, 2, 2)
y = torch.empty(2, 2, 2)
x, y

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 tensor([[[0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],
 
         [[2.3640e+14, 1.4013e-45],
          [0.0000e+00, 0.0000e+00]]]))

In [11]:
print(x.size())
x.shape

torch.Size([2, 2, 2])


torch.Size([2, 2, 2])

In [13]:
x = torch.tensor([1,3,5,7], dtype= torch.float64)
x

tensor([1., 3., 5., 7.], dtype=torch.float64)

In [18]:
x = torch.ones(2,2)
y = torch.ones(2,2)
print(x+y)
print(y)
y.add_(x)
print(y)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [27]:
print(y.size())
print(y.view(4, -1).size())

torch.Size([2, 2])
torch.Size([4, 1])


In [34]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
x = torch.rand(2,2,2,2,)
x = x.to(device)
print(device)
print(x, x.device)

mps
tensor([[[[0.8533, 0.8358],
          [0.3470, 0.7557]],

         [[0.4772, 0.3056],
          [0.2351, 0.2489]]],


        [[[0.6525, 0.4228],
          [0.4391, 0.7473]],

         [[0.4700, 0.2101],
          [0.3870, 0.0651]]]], device='mps:0') mps:0


In [54]:
x = torch.ones(3, requires_grad=True)
y = x + 0
print(x)
print(y)
print(y.grad_fn)

tensor([1., 1., 1.], requires_grad=True)
tensor([1., 1., 1.], grad_fn=<AddBackward0>)


In [55]:
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)
tensor(3., grad_fn=<MeanBackward0>)


In [56]:
print(x.grad)
z.backward()
print(x.grad)

None
tensor([2., 2., 2.])


Linear Regression

In [10]:
import torch
X = torch.arange(1,9, dtype=torch.float32)
Y = torch.arange(2,17,2, dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

def forward(x):
    return w * x

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

X_test = 5.0

print(f"Pred bf training: f({X_test}) = {forward(X_test).item():.3f}")

Pred bf training: f(5.0) = 0.000


In [14]:
learning_rate = 0.01
n_epochs = 100
for epoch in range(n_epochs):
    y_pred = forward(X)
    
    l = loss(Y, y_pred)
    
    l.backward()
    
    with torch.no_grad():
        w -= learning_rate * w.grad
    
    w.grad.zero_()
    
    if (epoch+1) % 10 ==0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss={l.item():.3f}')

print(f"Pred after training: f({X_test}) = {forward(X_test).item():.3f}")


epoch 10: w = 2.000, loss=0.000
epoch 20: w = 2.000, loss=0.000
epoch 30: w = 2.000, loss=0.000
epoch 40: w = 2.000, loss=0.000
epoch 50: w = 2.000, loss=0.000
epoch 60: w = 2.000, loss=0.000
epoch 70: w = 2.000, loss=0.000
epoch 80: w = 2.000, loss=0.000
epoch 90: w = 2.000, loss=0.000
epoch 100: w = 2.000, loss=0.000
Pred after training: f(5.0) = 10.000


In [7]:
import torch
import torch.nn as nn

X = torch.arange(1, 9, dtype=torch.float32).view(-1, 1)
Y = torch.arange(2, 18, 2, dtype=torch.float32).view(-1, 1)

n_samples, n_features = X.shape

X_test = torch.tensor([5], dtype=torch.float32)

(tensor([5.]), 5.0)

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim) -> None:
        super(LinearRegression, self).__init__()
        self.lin = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        return self.lin(x)

input_size, output_size = n_features, n_features

model = LinearRegression(input_size, output_size)

print(f'Prediction before training: f({X_test.item()}) = {model(X_test).item():.3f}\n')

learning_rate = 0.01
n_epochs = 100

loss = nn.MSELoss